### ISSUE TITLE
Getting Error while importing 

### ISSUE THREAD

**Issue by gerson-ribeiro** [jinhduong/ng2-jsgrid#4]
Hi Guys!

I'm getting the following error while import GridModule on the first step of the tutorial.

`**GridModule.forRoot** returns a **ModuleWithProviders** type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors`.

My projects are all in version 9.0 of angular.

Thank you very much in advance

**Comment by jinhduong** [comment]
@gerson-ribeiro sorry but we no longer support this library already
